import type {
  EventRow,
  League,
  MembershipPlan,
  MenuCategory,
  MenuItem,
  OpeningUpdate,
  Program,
} from "@/types";

/**
 * Static fallbacks mirroring supabase/seed.sql. Used when Supabase
 * is not configured (fresh clone, preview deploy) so every page
 * renders with realistic content instead of empty states.
 */

export const FALLBACK_LEAGUES: League[] = [
  {
    id: "fallback-league-1",
    name: "Men's Winter League",
    slug: "mens-winter-league",
    category: "mens",
    description:
      "A friendly, competitive 8-week league played on championship courses. Two-player teams, weekly matchups and season standings.",
    season: "Winter 2026–27",
    registration_opens_at: null,
    registration_closes_at: null,
    starts_at: null,
    ends_at: null,
    day_of_week: 2,
    start_time: "18:00",
    capacity: 32,
    team_size: 2,
    price_cents: 12000,
    status: "interest",
    rules: null,
    featured_image_url: null,
  },
  {
    id: "fallback-league-2",
    name: "Ladies' League",
    slug: "ladies-league",
    category: "ladies",
    description:
      "A welcoming league for women of all skill levels — equal parts golf, coaching tips and social time.",
    season: "Winter 2026–27",
    registration_opens_at: null,
    registration_closes_at: null,
    starts_at: null,
    ends_at: null,
    day_of_week: 3,
    start_time: "18:00",
    capacity: 24,
    team_size: 2,
    price_cents: 12000,
    status: "interest",
    rules: null,
    featured_image_url: null,
  },
  {
    id: "fallback-league-3",
    name: "Couples League",
    slug: "couples-league",
    category: "couples",
    description:
      "Team up with your favorite playing partner for a relaxed evening league with a social format.",
    season: "Winter 2026–27",
    registration_opens_at: null,
    registration_closes_at: null,
    starts_at: null,
    ends_at: null,
    day_of_week: 4,
    start_time: "19:00",
    capacity: 24,
    team_size: 2,
    price_cents: 14000,
    status: "interest",
    rules: null,
    featured_image_url: null,
  },
  {
    id: "fallback-league-4",
    name: "Senior Day Play",
    slug: "senior-day-play",
    category: "senior",
    description:
      "Daytime sessions for seniors with flexible formats, coffee and unhurried tee times.",
    season: "Ongoing",
    registration_opens_at: null,
    registration_closes_at: null,
    starts_at: null,
    ends_at: null,
    day_of_week: 3,
    start_time: "10:00",
    capacity: 16,
    team_size: 1,
    price_cents: 6000,
    status: "interest",
    rules: null,
    featured_image_url: null,
  },
  {
    id: "fallback-league-5",
    name: "Business Team League",
    slug: "business-team-league",
    category: "business",
    description:
      "Company vs. company team golf — a fun standing reason to get your team out of the office.",
    season: "Winter 2026–27",
    registration_opens_at: null,
    registration_closes_at: null,
    starts_at: null,
    ends_at: null,
    day_of_week: 1,
    start_time: "18:30",
    capacity: 24,
    team_size: 4,
    price_cents: 32000,
    status: "interest",
    rules: null,
    featured_image_url: null,
  },
  {
    id: "fallback-league-6",
    name: "Church Team League",
    slug: "church-team-league",
    category: "church",
    description:
      "Fellowship-first team league for area congregations. All skill levels welcome.",
    season: "Winter 2026–27",
    registration_opens_at: null,
    registration_closes_at: null,
    starts_at: null,
    ends_at: null,
    day_of_week: 4,
    start_time: "18:30",
    capacity: 24,
    team_size: 4,
    price_cents: 28000,
    status: "interest",
    rules: null,
    featured_image_url: null,
  },
  {
    id: "fallback-league-7",
    name: "The Bunker Opening Tournament",
    slug: "opening-tournament",
    category: "tournament",
    description:
      "Our inaugural tournament — a scramble format open to all, with prizes and plenty of fanfare.",
    season: "Fall 2026",
    registration_opens_at: null,
    registration_closes_at: null,
    starts_at: null,
    ends_at: null,
    day_of_week: null,
    start_time: null,
    capacity: 48,
    team_size: 4,
    price_cents: 10000,
    status: "opening_soon",
    rules: null,
    featured_image_url: null,
  },
];

export const FALLBACK_PROGRAMS: Program[] = [
  {
    id: "fallback-program-1",
    name: "Private Lesson",
    slug: "private-lesson",
    category: "private_lesson",
    description:
      "One-on-one instruction tailored to your goals, using simulator ball-flight data to guide each session.",
    instructor_id: null,
    age_min: null,
    age_max: null,
    skill_level: "all",
    starts_at: null,
    ends_at: null,
    capacity: 1,
    price_cents: 6500,
    duration_minutes: 60,
    what_to_bring: null,
    status: "interest",
  },
  {
    id: "fallback-program-2",
    name: "Beginner Basics",
    slug: "beginner-basics",
    category: "beginner_lesson",
    description:
      "Never held a club? Perfect. A relaxed introduction to grip, stance and swing in a private bay.",
    instructor_id: null,
    age_min: null,
    age_max: null,
    skill_level: "new",
    starts_at: null,
    ends_at: null,
    capacity: 4,
    price_cents: 4500,
    duration_minutes: 60,
    what_to_bring: null,
    status: "interest",
  },
  {
    id: "fallback-program-3",
    name: "Swing Evaluation",
    slug: "swing-evaluation",
    category: "swing_evaluation",
    description: "A data-driven look at your swing with clear takeaways and a practice plan.",
    instructor_id: null,
    age_min: null,
    age_max: null,
    skill_level: "all",
    starts_at: null,
    ends_at: null,
    capacity: 1,
    price_cents: 5500,
    duration_minutes: 45,
    what_to_bring: null,
    status: "interest",
  },
  {
    id: "fallback-program-4",
    name: "Junior Golf Clinic",
    slug: "junior-golf-clinic",
    category: "youth_clinic",
    description:
      "Small-group clinics that make golf fun first — games, challenges and fundamentals for young golfers.",
    instructor_id: null,
    age_min: 7,
    age_max: 14,
    skill_level: "all",
    starts_at: null,
    ends_at: null,
    capacity: 8,
    price_cents: 9000,
    duration_minutes: 60,
    what_to_bring: null,
    status: "interest",
  },
  {
    id: "fallback-program-5",
    name: "Junior League",
    slug: "junior-league",
    category: "junior_league",
    description:
      "A team-based league for young golfers with weekly play and friendly coaching.",
    instructor_id: null,
    age_min: 10,
    age_max: 17,
    skill_level: "all",
    starts_at: null,
    ends_at: null,
    capacity: 16,
    price_cents: 11000,
    duration_minutes: 90,
    what_to_bring: null,
    status: "interest",
  },
];

export const FALLBACK_EVENTS: EventRow[] = [
  {
    id: "fallback-event-1",
    title: "Community Open House",
    slug: "community-open-house",
    category: "community",
    excerpt: "Walk the space, try a swing and meet Jay and Amanda before we officially open.",
    description:
      "Come see what we've been building. Tour the bays, watch simulator demos, ask questions about leagues and memberships, and enjoy light refreshments. Family friendly and free to attend.",
    starts_at: "2026-09-19T19:00:00.000Z",
    ends_at: "2026-09-20T00:00:00.000Z",
    location: "The Bunker — Linton, Indiana",
    capacity: null,
    price_cents: null,
    registration_required: false,
    status: "published",
    image_url: null,
    featured: true,
  },
  {
    id: "fallback-event-2",
    title: "Highland Stage Preview Night",
    slug: "highland-stage-preview-night",
    category: "highland_stage",
    excerpt: "A first look at our community stage with live acoustic music and an open lounge.",
    description:
      "The Highland Stage is our home for live entertainment and community programming. Join us for a preview evening with local musicians, drinks and a relaxed clubhouse atmosphere.",
    starts_at: "2026-10-02T22:00:00.000Z",
    ends_at: "2026-10-03T01:00:00.000Z",
    location: "The Bunker — Linton, Indiana",
    capacity: null,
    price_cents: null,
    registration_required: false,
    status: "published",
    image_url: null,
    featured: true,
  },
  {
    id: "fallback-event-3",
    title: "Simulator Demo Weekend",
    slug: "simulator-demo-weekend",
    category: "golf",
    excerpt: "Free 15-minute demo sessions all weekend — first come, first served.",
    description:
      "Curious how a golf simulator works? Drop in during demo weekend and our team will get you hitting shots on world-famous courses in minutes. All ages and skill levels welcome.",
    starts_at: "2026-10-10T14:00:00.000Z",
    ends_at: "2026-10-11T22:00:00.000Z",
    location: "The Bunker — Linton, Indiana",
    capacity: null,
    price_cents: null,
    registration_required: false,
    status: "published",
    image_url: null,
    featured: false,
  },
];

export const FALLBACK_MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: "fallback-plan-1",
    name: "Practice",
    slug: "practice",
    description: "For regulars who want consistent practice time each month.",
    billing_interval: "month",
    price_cents: 7900,
    stripe_price_id: null,
    included_minutes: 240,
    rollover_rule: "none",
    booking_window_days: 10,
    discount_percentage: 10,
    household_eligible: false,
    sort_order: 1,
    active: true,
  },
  {
    id: "fallback-plan-2",
    name: "Player",
    slug: "player",
    description: "More included time, league discounts and priority tournament access.",
    billing_interval: "month",
    price_cents: 12900,
    stripe_price_id: null,
    included_minutes: 480,
    rollover_rule: "none",
    booking_window_days: 14,
    discount_percentage: 15,
    household_eligible: false,
    sort_order: 2,
    active: true,
  },
  {
    id: "fallback-plan-3",
    name: "Family",
    slug: "family",
    description:
      "Shared household benefits with youth program discounts and guest privileges.",
    billing_interval: "month",
    price_cents: 17900,
    stripe_price_id: null,
    included_minutes: 600,
    rollover_rule: "none",
    booking_window_days: 14,
    discount_percentage: 15,
    household_eligible: true,
    sort_order: 3,
    active: true,
  },
  {
    id: "fallback-plan-4",
    name: "Business",
    slug: "business",
    description:
      "Shared company credits, employee access and event discounts with central billing.",
    billing_interval: "month",
    price_cents: 24900,
    stripe_price_id: null,
    included_minutes: 900,
    rollover_rule: "none",
    booking_window_days: 14,
    discount_percentage: 15,
    household_eligible: true,
    sort_order: 4,
    active: true,
  },
];

interface MenuData {
  categories: MenuCategory[];
  items: MenuItem[];
}

const cat = (id: string, name: string, slug: string, description: string, sort: number): MenuCategory => ({
  id,
  name,
  slug,
  description,
  sort_order: sort,
  active: true,
});

const item = (
  id: string,
  category_id: string,
  name: string,
  description: string,
  price_cents: number,
  dietary_labels: string[],
  featured: boolean,
  sort_order: number,
): MenuItem => ({
  id,
  category_id,
  name,
  description,
  price_cents,
  image_url: null,
  dietary_labels,
  allergen_notes: null,
  available: true,
  featured,
  sort_order,
});

export const FALLBACK_MENU: MenuData = {
  categories: [
    cat("mc-1", "Shareables", "shareables", "Made for the whole bay.", 1),
    cat("mc-2", "Snacks", "snacks", "Quick bites between shots.", 2),
    cat("mc-3", "Sandwiches", "sandwiches", "Hearty enough for 18 holes.", 3),
    cat("mc-4", "Kids", "kids", "For the junior members of your group.", 4),
    cat("mc-5", "Desserts", "desserts", "Finish strong.", 5),
    cat("mc-6", "Drinks", "drinks", "Sodas, coffee and more.", 6),
    cat("mc-7", "Beer & Wine", "beer-wine", "Local favorites and clubhouse classics.", 7),
  ],
  items: [
    item("mi-1", "mc-1", "Clubhouse Pretzel Bites", "Warm pretzel bites with beer cheese and honey mustard.", 950, ["vegetarian"], true, 1),
    item("mi-2", "mc-1", "Loaded Bunker Nachos", "Tortilla chips, queso, pico, jalapeños and your choice of chicken or pork.", 1250, [], true, 2),
    item("mi-3", "mc-1", "Fairway Flatbread", "Rotating flatbread with seasonal toppings — ask what's on this week.", 1150, [], false, 3),
    item("mi-4", "mc-2", "Kettle Chips & Dip", "House kettle chips with French onion dip.", 550, ["vegetarian", "gluten-conscious"], false, 1),
    item("mi-5", "mc-2", "Mixed Nuts", "Roasted and lightly salted.", 450, ["vegan", "gluten-conscious", "contains-nuts"], false, 2),
    item("mi-6", "mc-3", "The Turn Club", "Turkey, ham, bacon, lettuce, tomato and mayo on toasted sourdough.", 1150, [], true, 1),
    item("mi-7", "mc-3", "Pulled Pork Sandwich", "Slow-smoked pork with tangy slaw on a brioche bun.", 1150, [], false, 2),
    item("mi-8", "mc-4", "Chicken Tenders & Chips", "Three crispy tenders with kettle chips.", 700, [], false, 1),
    item("mi-9", "mc-4", "Grilled Cheese", "Classic grilled cheese on Texas toast.", 600, ["vegetarian"], false, 2),
    item("mi-10", "mc-5", "Warm Cookie Skillet", "Chocolate chip cookie baked to order with vanilla ice cream.", 800, ["vegetarian", "contains-nuts"], true, 1),
    item("mi-11", "mc-6", "Fountain Sodas", "Coke products with free refills.", 300, ["vegan"], false, 1),
    item("mi-12", "mc-6", "Fresh Coffee", "Locally roasted drip coffee.", 350, ["vegan"], false, 2),
    item("mi-13", "mc-7", "Local Draft Selection", "Rotating Indiana craft drafts — ask what's pouring.", 650, [], false, 1),
    item("mi-14", "mc-7", "House Wine", "Red or white by the glass.", 750, [], false, 2),
  ],
};

export const FALLBACK_UPDATES: OpeningUpdate[] = [
  {
    id: "fallback-update-2",
    title: "Construction Underway",
    slug: "construction-underway",
    excerpt: "Walls are going up and bay layouts are locked in. Here's a look at the progress.",
    content:
      "Construction is officially underway. This month the crew finished demo and framing for the simulator bays, the Highland Stage corner and the lounge. Next up: electrical, screens and turf.\n\nWant to be first to know when league registration and bay reservations open? Join the opening list and pick the programs you're interested in.",
    image_url: null,
    published_at: "2026-07-01T13:00:00.000Z",
    status: "published",
  },
  {
    id: "fallback-update-1",
    title: "The Bunker is Coming to Linton",
    slug: "the-bunker-is-coming-to-linton",
    excerpt:
      "Jay and Amanda are bringing year-round indoor golf to Greene County — opening Fall 2026.",
    content:
      "We're thrilled to officially announce The Bunker Indoor Golf, opening in Linton in Fall 2026. Our vision is simple: a year-round place to play, learn, compete and connect — whether you've played golf your whole life or you've never picked up a club.\n\nThe Bunker will feature state-of-the-art simulator bays, a putting green, private lessons, leagues for every kind of player, youth programs and a comfortable lounge with food and drinks.\n\nFollow along here for construction updates, league announcements and your first chance to book a bay.",
    image_url: null,
    published_at: "2026-06-01T13:00:00.000Z",
    status: "published",
  },
];
